@echo off
echo [GANGNIAGA] Starting Auto Push...
cd /d C:\Users\megat\GANGNIAGA-OS-UPGRADE\GANGNIAGA-OS
echo Adding files...
git add .
echo Committing...
git commit -m "feat: V0.4.0 Hermes integration + Content Studio + No OpenAI"
echo Pushing to main...
git push origin main
echo [DONE] Selesai! Bo, check GitHub sekarang.
pause